spring:
  application.name: gateway
  cloud:
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      #================
      #id does not have to match the path
      - id: cards
        uri: lb://flashcard
        predicates:
        - Path=/flashcard/**
        filters:
        - StripPrefix=1
        - name: CircuitBreaker
          args: 
            name: flashcard-fallback
            fallbackUri: forward:/fallback/flashcard
      #================
      - id: quiz
        uri: lb://quiz
        predicates:
        - Path=/quiz/**
        filters:
        - StripPrefix=1
       
